Cosmetics
color set, message strings and a penguin.
Indicate (or prefix) (most?) boot messages which display user changed settings with "++" and default settings with "::".

diff --git a/etc/init.d/tc-config b/etc/init.d/tc-config
--- a/etc/init.d/tc-config
+++ b/etc/init.d/tc-config
@@ -4,8 +4,27 @@
 # Several modifications for speed by Curaga
 # Several modifications for slowness by Misalf...
 # + Set alternate font (e.g. Terminus) for console (setconmap.sh).
+# + Cosmetics (color set, message strings and a penguin).
+# + Indicate (or prefix) (most?) boot messages which display user changed settings with "++" and default settings with "::".
 . /etc/init.d/tc-functions
 useBusybox
+
+#echo -en "\e]P0222222" #black    -> this is the background color as well. 
+echo -en "\e]P84F4F4F" #darkgray
+echo -en "\e]P1b00000" #darkred
+echo -en "\e]P9D92B2B" #red
+echo -en "\e]P24e9a06" #darkgreen
+echo -en "\e]PA81D92B" #green
+echo -en "\e]P3c4a000" #brown
+echo -en "\e]PBFCE632" #yellow
+echo -en "\e]P43465a4" #darkblue
+echo -en "\e]PC689ACF" #blue
+echo -en "\e]P575507b" #darkmagenta
+echo -en "\e]PDAD76A7" #magenta
+echo -en "\e]P606989a" #darkcyan
+echo -en "\e]PE34e2e2" #cyan
+echo -en "\e]P7d3d7cf" #lightgray
+echo -en "\e]PFeeeeec" #white   -> this is the foreground color as well.
 
 USER="tc"
 TCEDIR="/tmp/tce"
@@ -14,10 +33,14 @@ TCLOOP="/tmp/tcloop"
 TCEINSTALLED="/usr/local/tce.installed"
 INSTALLED=""
 VERSION="$(getFullVer)"
+ISSUE="$(cat /etc/issue)"
 KERNEL="$(uname -r)"
 
+DGRAY="$(echo -e '\033[1;30m')"
+ORANGE="$(echo -e '\033[0;33m')"
+
 addUser(){
-	echo "${GREEN}Adding user ${YELLOW}$USER ${NORMAL}"
+	echo "${DGRAY}++ ${GREEN}Adding user ${YELLOW}$USER ${NORMAL}"
 	/usr/sbin/adduser -s /bin/sh -G staff -D "$USER"
 	echo "$USER":tcuser | /usr/sbin/chpasswd -m
 	echo -e "$USER\tALL=NOPASSWD: ALL" >> /etc/sudoers
@@ -29,12 +52,15 @@ addUser(){
 
 [ -x /usr/local/bin/setconmap.sh ] && /usr/local/bin/setconmap.sh
 
-echo "${GREEN}Booting ${YELLOW}Core $VERSION ${NORMAL}"
-echo "${GREEN}Running Linux Kernel ${YELLOW}$KERNEL${GREEN}.${NORMAL}"
+echo " "
+echo -e "  \033[1;30m(\033[0;37m°\033[0;33m- "
+echo -e "  \033[1;30m//\033[0;37m\   \033[0;32mBooting \033[0;33m${ISSUE} \033[1;33m${VERSION}\033[1;30m :: \033[0;32mKernel \033[1;33m${KERNEL}"
+echo -e "  \033[1;30mV_\033[0;37m/\033[0;33m_"
+echo -e "\033[00m"
 export PATH=/usr/local/sbin:/usr/local/bin:"$PATH"
 
 # Here we check all the boot parameters using the fastest way known to men, case & loop
-echo -n "${BLUE}Checking boot options...${NORMAL}"
+echo -n "${DGRAY}:: ${BLUE}Checking boot options${DGRAY} ...${NORMAL}"
 for i in `cat /proc/cmdline`; do
 	case $i in
 		*=*)
@@ -93,7 +119,7 @@ for i in `cat /proc/cmdline`; do
 		;;
 	esac
 done
-echo "${GREEN} Done.${NORMAL}"
+echo "${DGRAY}Done${NORMAL}"
 
 if [ -n "$BLACKLIST" ]; then
 	mkdir -p /etc/modprobe.d
@@ -105,26 +131,34 @@ if [ -n "$BLACKLIST" ]; then
 fi
 
 # Start Udev to populate /dev and handle hotplug events
-echo -n "${BLUE}Starting udev daemon for hotplug support...${NORMAL}"
+echo -n "${DGRAY}:: ${BLUE}udev daemon for hotplug${DGRAY} ...${NORMAL}"
 #/sbin/udevd --daemon 2>/dev/null >/dev/null
 /sbin/udevd --daemon 2>&1 >/dev/null
 #/sbin/udevadm trigger --action=add 2>/dev/null >/dev/null &
 /sbin/udevadm trigger --action=add 2>&1 >/dev/null &
+echo -n "${YELLOW}"
 rotdash $!
-echo "${GREEN} Done.${NORMAL}"
+echo "${DGRAY}Done${NORMAL}"
 
 [ -n "$WAITUSB" ] && (
 	case $WAITUSB in
 		*:*) dev=${WAITUSB#*:}
 		timeout=$((${WAITUSB%:*} * 4))
 		while [ $timeout -gt 0 ]; do
-			echo -en "${BLUE}\rWaiting as requested... ${NORMAL}$(($timeout / 4)) "
+			echo -en "\r${DGRAY}++ ${BLUE}Waiting ${DGRAY}<${NORMAL}$(($timeout / 4))${DGRAY}>${BLUE} sec for device ${YELLOW}$dev${NORMAL} "
 			timeout=$(($timeout - 1))
 			blkid -lt $dev >/dev/null && timeout=0 || sleep 0.25
 		done
 		echo
 		;;
-		*) sleep "$WAITUSB" ;;
+		*)
+		while [ $WAITUSB -gt 0 ]; do
+			echo -en "\r${DGRAY}:: ${BLUE}Waiting ${DGRAY}<${NORMAL}$WAITUSB${DGRAY}>${BLUE} sec for nothing${NORMAL} "
+			WAITUSB=$(($WAITUSB - 1))
+			sleep $WAITUSB
+		done
+		echo
+		;;
 	esac
 )
 
@@ -132,7 +166,7 @@ modprobe loop 2>/dev/null
 #modprobe ohci_hcd
 
 if [ -n "$NOZSWAP" ]; then
-	echo "${BLUE}Skipping compressed swap in ram as requested from the boot command line.${NORMAL}"
+	echo "${DGRAY}++ Skipping compressed swap in ram (nozswap).${NORMAL}"
 else
 	while [ ! -e /dev/zram0 ]; do usleep 50000; done
 	grep MemFree /proc/meminfo | awk '{printf("%dK\n", $2/4)}' > /sys/block/zram0/disksize
@@ -143,28 +177,33 @@ else
 fi
 
 if [ -n "$NOFSTAB" ]; then
-	echo "${BLUE}Skipping /etc/fstab creation as requested from the boot command line.${NORMAL}"
+	echo "${DGRAY}++ Skipping /etc/fstab creation (nofstab).${NORMAL}"
 else
-	echo "${BLUE}Scanning hard disk partitions to create ${YELLOW}/etc/fstab ${NORMAL}"
+	echo "${DGRAY}:: ${BLUE}Scanning partitions to create ${YELLOW}/etc/fstab ${NORMAL}"
 	/usr/sbin/rebuildfstab & fstab_pid=$!
 	mv /tmp/98-tc.rules /etc/udev/rules.d/. 2>/dev/null
 	/sbin/udevadm control --reload-rules &
 fi
-
-[ -n "$LANGUAGE" ] || LANGUAGE="C"
-echo -n "${GREEN}Setting Language to ${MAGENTA}$LANGUAGE"
+#[ -n "$LANGUAGE" ] || LANGUAGE="C"
+if [ -n "$LANGUAGE" ]; then
+	echo -n "${DGRAY}++ "
+else
+	LANGUAGE="C"
+	echo -n "${DGRAY}:: "
+fi
+echo -n "${GREEN}Language${DGRAY}: "
 echo "LANG=$LANGUAGE" > /etc/sysconfig/language
 export LANG=$LANGUAGE
-echo "${GREEN} Done.${NORMAL}"
+echo "${MAGENTA}$LANGUAGE${NORMAL}"
 
 if [ -n "$TZ" ]; then
-	echo -n "${GREEN}Setting Timezone to ${MAGENTA}$TZ"
+	echo -n "${DGRAY}++ ${GREEN}Timezone${DGRAY}: "
 	export TZ && echo "TZ=$TZ" > /etc/sysconfig/timezone
-	echo "${GREEN} Done.${NORMAL}"
+	echo "${MAGENTA}$TZ${NORMAL}"
 fi	
 
 if [ -n "$NORTC" ]; then
-	echo "${BLUE}Skipping rtc as requested from the boot command line.${NORMAL}"
+	echo "${DGRAY}++ Skipping rtc (nortc).${NORMAL}"
 else
 	while [ ! -e /dev/rtc0 ]; do usleep 50000; done
 	if [ -n "$NOUTC" ]; then
@@ -177,13 +216,14 @@ fi
 if [ -n "$HOST" ]; then
 	sethostname
 else
+	echo "${DGRAY}:: ${GREEN}Hostname${DGRAY}: ${MAGENTA}`cat /etc/hostname`${NORMAL} "
 	/bin/hostname -F /etc/hostname
 fi
 
 if [ -n "$SYSLOG" ]; then
 	 [ -z "$RSYSLOG" ] || SOPTS=" -R $RSYSLOG -L "
-	 /sbin/syslogd ${SOPTS} && echo "${GREEN}syslog started.${NORMAL}"
-	 /sbin/klogd && echo "${GREEN}klog started."
+	 /sbin/syslogd ${SOPTS} && echo "${DGRAY}++ ${GREEN}syslog started ${NORMAL}"
+	 /sbin/klogd && echo "${DGRAY}++ ${GREEN}klog started ${NORMAL}"
 fi
 
 /sbin/ifconfig lo 127.0.0.1 up
@@ -194,7 +234,7 @@ if [ -n "$AOE" ]; then
 	DEV=$( echo $AOE | awk -F: '{ print $2 }')
 	ifconfig $IFACE up
 	modprobe aoe
-	echo "${BLUE}Waiting for $DEV${NORMAL}"
+	echo "${DGRAY}++ ${BLUE}Waiting for $DEV${NORMAL}"
 	CNT=120
 	until [ -e /dev/etherd/interfaces ]
 	do
@@ -283,7 +323,7 @@ get_app() {
 		cd $TCE
 		[ "$PROTO" = "TFTP" ] && tftp -g -r $FILE $HOST
 		[ "$PROTO" = "HTTP" ] && wget -q http://${HOST}/${FILE}
-		[ $SHOWAPPS ] && echo -ne "${BLUE}TFTP Loading Extensions ${YELLOW}"
+		[ $SHOWAPPS ] && echo -ne "${DGRAY}++ ${BLUE}TFTP Loading Extensions${DGRAY}... ${YELLOW}"
 		dos2unix -u $NAME
 		while read FILE FL
 		do
@@ -294,7 +334,7 @@ get_app() {
 			su "$USER" -c "$LOADER $FL $TCE/$APP"
 			[ "$FL" == "-c" ] && rm $APP
 		done < $NAME
-		[ $SHOWAPPS ] && echo "${GREEN} Done.${NORMAL}"
+		[ $SHOWAPPS ] && echo "${DGRAY}Done${NORMAL}"
 		rm $NAME
 	)
 }
@@ -400,7 +440,7 @@ fi
 
 if grep -q "^/dev/root" /proc/mounts; then
 	INSTALLED=1
-	echo "${RED}Detected Traditional Hard drive installation.${NORMAL}"
+	echo "${DGRAY}** ${RED}Detected Traditional Hard drive installation${DGRAY}.${NORMAL}"
 fi
 
 /sbin/ldconfig 2>/dev/null
@@ -457,7 +497,7 @@ if [ -n "$MYHOME" ]; then
 		esac
 
 	else
-		echo "Invalid device specified. Ignoring persistent HOME request!"
+		echo "${DGRAY}** ${RED}Invalid device specified - Ignoring persistent HOME request${DGRAY}!${NORMAL}"
 	fi
 fi
 
@@ -496,7 +536,7 @@ if [ -n "$MYOPT" ]; then
 		esac
 
 	else
-		echo "Invalid device specified. Skipping persistent OPT request!"
+		echo "${DGRAY}** ${RED}Invalid device specified - Skipping persistent OPT request${DGRAY}!${NORMAL}"
 	fi
 fi
 
@@ -506,28 +546,31 @@ if [ -n "$LAPTOP" ]; then
 	modprobe ac && modprobe battery 2>/dev/null
 	modprobe yenta_socket >/dev/null 2>&1 || modprobe i82365 >/dev/null 2>&1
 	/sbin/udevadm trigger 2>/dev/null >/dev/null &
-	echo "${GREEN}Laptop options enabled (AC, Battery and PCMCIA).${NORMAL}"
+	echo "${DGRAY}++ ${GREEN}Laptop mode (AC, Battery and PCMCIA)${NORMAL}"
 fi
 
 if [ -n "$NOSWAP" ]; then
-	echo "${BLUE}Ignoring swap partition(s) seek as requested.${NORMAL}"
+	echo "${DGRAY}++ Skipping swap partitions seek (noswap).${NORMAL}"
 else
+	echo -n "${DGRAY}:: ${BLUE}Enabling possible swap partitions${NORMAL}"
 	wait $fstab_pid
 	/sbin/swapon -a 2>/dev/null
-	if [ "$?" == 0 ]; then echo "${GREEN}Possible swap partition(s) enabled.${NORMAL}"; fi
+	if [ "$?" == 0 ]; then echo "${GREEN} Done.${NORMAL}"; else echo "${RED} Fail.${NORMAL}"; fi
 fi
 
 if [ -n "$SWAPFILE" ]; then
+	echo -n "${DGRAY}++ ${BLUE}Enabling swap file on ${YELLOW}$SWAPFILE${NORMAL}"
 	wait $fstab_pid
 	SWAPFILE=${SWAPFILE##/dev/}
 	find_mountpoint "$SWAPFILE"
 	if [ -n "$MOUNTPOINT" ]; then
 		if [ "$MOUNTED" == "yes" ]; then
-			swapon "$MOUNTPOINT"/tc.swp
+			swapon "$MOUNTPOINT"/tc.swp && SWAPFILE_SUCCESS=1
 		else
-			mount "$MOUNTPOINT" && swapon "$MOUNTPOINT"/tc.swp
+			mount "$MOUNTPOINT" && swapon "$MOUNTPOINT"/tc.swp && SWAPFILE_SUCCESS=1
 		fi
 	fi
+	[ $SWAPFILE_SUCCESS ] && echo "${GREEN} Done.${NORMAL}" || echo "${RED} Fail.${NORMAL}"
 fi
 
 if [ -n "$RESUME" ]; then
@@ -556,36 +599,43 @@ fi
 sync
 
 wait $fstab_pid
-MSSG="${BLUE}Loading extensions...${NORMAL}"
+MSSG="${DGRAY}:: ${BLUE}Loading extensions${DGRAY} ...${NORMAL}"
 if [ -n "$SHOWAPPS" ]; then
 	touch /etc/sysconfig/showapps
-	echo "$MSSG"
+	echo -n "$MSSG "
 	/usr/bin/tce-setup "booting" 
 	[ -n "$ISOFILE" ] && /usr/bin/fromISOfile "$ISOFILE"
 	rm /etc/sysconfig/showapps
-	echo "${GREEN} Done.${NORMAL}"
+	echo "${DGRAY}Done${NORMAL}"
 else
 	echo -n "$MSSG"
 	/usr/bin/tce-setup "booting" > /dev/null 2>&1 & 
+	echo -n "${YELLOW}"
 	rotdash $!
+	echo -n "${NORMAL}"
 	[ -n "$ISOFILE" ] && /usr/bin/fromISOfile "$ISOFILE" > /dev/null 2>&1 &
+	echo -n "${YELLOW}"
 	rotdash $!
-	echo "${GREEN} Done.${NORMAL}"
+	echo "${DGRAY}Done${NORMAL}"
 	if [ -s /tmp/aberr ]; then
-		echo "${RED}Warning! Errors occured during the loading of the extensions.${YELLOW}"
+		echo "${DGRAY}** ${RED}Warning! Errors occured during the loading of the extensions${DGRAY}.${YELLOW}"
 		cat /tmp/aberr
-		echo -n "${RED}Press Enter key.${NORMAL}"; read ans
+		echo -n "${DGRAY}** ${RED}Press Enter key${DGRAY}.${NORMAL}"; read ans
 	fi
 fi
 
 [ -x /usr/local/bin/setconmap.sh ] && /usr/local/bin/setconmap.sh
 
-[ -n "$KEYMAP" ] || KEYMAP="us"
+if [ -n "$KEYMAP" ]; then
+	echo -n "${DGRAY}++ "
+else
+	KEYMAP="us"
+	echo -n "${DGRAY}:: "
+fi
 if [ -f "/usr/share/kmap/$KEYMAP.kmap" ]; then
-	echo -n "${GREEN}Setting keymap to ${MAGENTA}$KEYMAP"
+	echo "${GREEN}Keymap${DGRAY}: ${MAGENTA}$KEYMAP${NORMAL}"
 	/sbin/loadkmap < /usr/share/kmap/$KEYMAP.kmap
 	echo "KEYMAP=$KEYMAP" > /etc/sysconfig/keymap
-	echo "${GREEN} Done.${NORMAL}"
 fi
 
 if [ -n "$SECURE" ]; then
@@ -606,8 +656,10 @@ fi
 # If desktop is specified use that
 if [ -n "$DESKTOP" ]; then
 	echo "$DESKTOP" > /etc/sysconfig/desktop
+	echo "${DGRAY}++ ${GREEN}Desktop${DGRAY}: ${MAGENTA}$DESKTOP${NORMAL}"
 else
 	[ -s /etc/sysconfig/desktop ] && DESKTOP=`cat /etc/sysconfig/desktop`
+	[ -n "$DESKTOP" ]  && echo "${DGRAY}:: ${GREEN}Desktop${DGRAY}: ${BLUE}$DESKTOP${NORMAL}"
 fi
 
 # If ntpserver is specified use that
@@ -624,21 +676,26 @@ else
 	echo "mydata" > /etc/sysconfig/mydata
 fi   
 if [ -n "$NORESTORE" ]; then
-	echo "${GREEN}Skipping restore as requested from the command line.${NORMAL}"
+	echo "${DGRAY}++ Skipping backup files restore (norestore).${NORMAL}"
 else
 	TCEDIR=`readlink /etc/sysconfig/tcedir`
+	[ -n "$MYDATA" ] && echo -n "${DGRAY}++ ${BLUE}" || echo -n "${DGRAY}:: ${BLUE}"
 	/etc/init.d/tc-restore.sh "$TCEDIR"
+	echo -n "${NORMAL}"
 fi
 
 # After restore items
 if [ -n "$NODHCP" ]; then
-	echo "${GREEN}Skipping DHCP broadcast/network detection as requested on boot commandline.${NORMAL}"
+	echo "${DGRAY}++ Skipping DHCP broadcast/network detection (nodhcp).${NORMAL}"
 else
 	[ -z "$DHCP_RAN" ] && /etc/init.d/dhcp.sh &
 	[ -z "$NORTC" ] || /etc/init.d/settime.sh &
 fi
 
-[ -n "$CRON" ] && /etc/init.d/services/crond start
+if [ -n "$CRON" ]; then
+	#/etc/init.d/services/crond start
+	/usr/sbin/crond -d 8 2>/dev/null && echo "${DGRAY}++ ${GREEN}cron started ${NORMAL}"
+fi
 
 /sbin/loadcpufreq 2>/dev/null &
 
@@ -647,7 +704,7 @@ fi
 [ -n "$NOAUTOLOGIN" ] && echo "booting" > /etc/sysconfig/noautologin
 
 if [ -n "$PAUSE" ]; then
-	echo -n "${BLUE}Boot time configuration completed. Press <Enter> to continue.${NORMAL}"
-	read junk
+	echo -e "\n${DGRAY}++ ${BLUE}Boot time configuration completed${DGRAY}.\n>> ${BLUE}Press the${RED} <${YELLOW}ANY${RED}> ${BLUE}key to continue${DGRAY}!${NORMAL}\n"
+	read -n1 junk
 fi
 
